################################################################################
# +-+-+-+-+-+-+-+-+-+-+-+-+-+ Database Information +-+-+-+-+-+-+-+-+-+-+-+-+-+-+
################################################################################
# The database information specifies where
# The information of the Plugin should be stored
# such as user data. If you do not know what MySQL is
# or how to operate a MySQL server leave the value as SQLite

# MySQL or SQLite [DEFAULT]
DatabaseType: SQLite

# Below defines the connection information
# for the MySQL database.
MySQL:
  # The Hostname of your SQL database
  # Example: localhost:3306 or 127.0.0.1:3306
  host: localhost:3306

  # The name of the Database to use
  db_name: creed_test

  # The username of your database
  user: creed

  # The password for the database user
  password: test

