# This is the plugin.yml for the CraftyProfessions plugin. As you can see below
# this plugin does depend on Vault in order to distribute the money
# earned to a separate economy plugin.
name: CraftyProfessions
version: 0.0.6
description: This is a Professions plugin which will be completely customizable.
main: com.magnarisa.spigot_craftyprofessions.CraftyProfessions
author: CreedTheFreak

depend: [Vault]
database: true

######################### Databases ########################
# There are Three different types of databases that are
# currently supported. SQLite which is a local database.
# MySQL through the connector/J of MariaDB, and then
# MariaDB itself. Simply put the database you would
# like to use within the Type Parameter.
#
# Types: SQLite [Default], MySQL, MariaDB
#
# The Host, Database, User, and Password should be
# used for MySQL or MariaDB but not SQLite.
#
DBMS:
  Type: SQLite
    # The URL to your database
    # Example: localhost:3306 or 127.0.0.1:3306
    host: null
    # The name of the Database to use
    db_name: null
    # The username of your database
    user: null
    # The password for the database user
    password: null


########################## Commands ########################
commands:
  prof:
    description: The entry point into the commands for CraftyProfessions
    usage: |
        Error False was returned from command!


### Random Commands for fun ###
  shower:
    description: The Shower Squad, That is all...
    usage: /<command>
    aliases: [shower, showersquad, showersqad, showersquad]


#################### Permissions ####################
#
# Input some sort of sassy description here
#
#
#
permissions:
  craftyprofessions.admin.*:
    default: op
    description: Give player all of the administration permissions

  craftyprofessions.use.*:
    default: op
    description: Give a player all of the use permissions

  craftyprofessions.db.*:
    default: op
    description: Give the player all of the Database permissions
