# This is the plugin.yml for the CommonWealth plugin. As you can see below
# this plugin does depend on Vault in order to distribute the money
# earned to a separate economy plugin.
name: CommonWealth
version: 0.0.2
description: This is a Jobs plugin which will be completely customizable.
main: magnarisa.commonwealth.CommonWealth
author: Logan Cookman

depend: [Vault]
soft depend: [CoreProtect]

# I may add in some sort of Database here we shall see
database: false

commands:
  shower:
    description: The Shower Command
    usage: /shower
